#!/bin/bash
threads=15
test=
prefix=
textlist=
name="epubjob_"
while test $# -gt 0; do
  case $1 in
    --prefix=*)  prefix=`echo $1 | sed 's/.*prefix=//'`;;
    --threads=*)  threads=`echo $1 | sed 's/.*threads=//'`;;
    --test=*)  test=`echo $1 | sed 's/.*test=//'`;;
    --textlist=*)  textlist=`echo $1 | sed 's/.*textlist=//'`;;
     *) if test "$1" = "${1#--}" ; then 
	   break
	else
	   echo "WARNING: Unrecognized option '$1' ignored. try --threads, --test or --textlist"
	fi ;;
  esac
  shift
done

if test "x$test" = "x"
then
    if  test "x$textlist" = "x"
    then
	find Texts-XML -name "$prefix*.xml" > list
	rm -f $name*
	split -l $(( `cat list | wc -l` / $threads)) list $name
	for i in $name*; do 
	    cat anthead.xml> $i.xml 
	    perl -p -e 's:Texts-XML/(.*)/(.*).xml:<doepub dir="Texts-XML/$1" outdir="Texts-EPUB/$1" name="$2"/>:' $i >>$i.xml
	    cat anttail.xml >> $i.xml
	    ANT_OPTS="-Xss2m -Xmx752m" time nohup ant -lib lib/saxon9he.jar:lib/jing.jar -Dbasedir=`pwd` -f $i.xml >& $i.LOG & 
	done
    else
	cat anthead.xml> test$name.xml 
	cat $textlist | perl -p -e 's:Texts-XML/(.*)/(.*).xml:<doepub dir="Texts-XML/$1" outdir="Texts-EPUB/$1" name="$2"/>:'   >> test$name.xml
	cat anttail.xml >> test$name.xml
	ANT_OPTS="-Xss2m -Xmx752m" ant -lib lib/saxon9he.jar:lib/jing.jar -Dbasedir=`pwd` -f test$name.xml 
    fi
else
    echo test $test
    cat anthead.xml> test$name.xml 
    echo $test | perl -p -e 's:Texts-XML/(.*)/(.*).xml:<doepub dir="Texts-XML/$1" outdir="Texts-EPUB/$1" name="$2"/>:'   >> test$name.xml
    cat anttail.xml >> test$name.xml
    ANT_OPTS="-Xss2m -Xmx752m" ant -lib lib/saxon9he.jar:lib/jing.jar -Dbasedir=`pwd` -f test$name.xml 
fi
