#!/bin/bash
threads=15
test=
prefix=
textlist=
xsl=/usr/share/xml/tei/stylesheet
source=.
name="convertjob_"
while test $# -gt 0; do
  case $1 in
    --xsl=*) xsl=`echo $1 | sed 's/.*xsl=//'`;;
    --prefix=*) prefix=`echo $1 | sed 's/.*prefix=//'`;;
    --source=*) source=`echo $1 | sed 's/.*source=//'`;;
    --threads=*)  threads=`echo $1 | sed 's/.*threads=//'`;;
    --test=*)  test=`echo $1 | sed 's/.*test=//'`;;
    --textlist=*)  textlist=`echo $1 | sed 's/.*textlist=//'`;;
     *) if test "$1" = "${1#--}" ; then 
	   break
	else
	   echo "WARNING: Unrecognized option '$1' ignored. try --threads, --test or --textlist"
	fi ;;
  esac
  shift
done
ANT_OPTS=" -Xss4m -Xmx1024m -Djdk.xml.entityExpansionLimit=0"
export ANT_OPTS
ANT_PARAMS="-lib lib/saxon9he.jar:lib/jing.jar -Dxsl=$xsl -Dbasedir=`pwd`"
ANT="ant  $ANT_PARAMS"
if test "x$test" = "x"
then
    if  test "x$textlist" = "x"
    then
        find $source/Texts-SGML -name "$prefix*.sgm" > list
	if  [ $threads -eq 1 ]
	then
		cat anthead.xml> convertall.xml 
		perl makejob.pl $source < list >> convertall.xml
		cat anttail.xml >> convertall.xml
		$ANT -f convertall.xml
	else
            rm -f $name*
            split -l $(( `cat list | wc -l` / $threads)) list $name
	    for i in $name*; do 
		cat anthead.xml> $i.xml 
		perl makejob.pl $source < $i >>$i.xml
		cat anttail.xml >> $i.xml
                nohup $ANT -f $i.xml >& $i.LOG & 
	    done
        fi
    else
	cat anthead.xml> test$name.xml 
	cat $textlist | perl makejob.pl $source   >> test$name.xml
	cat anttail.xml >> test$name.xml
	$ANT -f test$name.xml 
    fi
else
    echo test $test
    F=`basename $test .sgm`
    D=`echo $test | sed 's/\(...\).*/\1/'`
    cat anthead.xml> test$name.xml 
    echo "$D/$F.sgm" | perl makejob.pl $source  >> test$name.xml
    cat anttail.xml >> test$name.xml
     $ANT -f test$name.xml 
fi
