test:
	osx -ccatalog -xlower -xcomment -xempty -xndata test.sgm  | xmllint --format - > test.xml

charmap:
	osx -ccatalog -xlower -xcomment -xempty -xndata charmap.sgm  | xmllint --format - > charmap.xml

eebodat:
	osx -ccatalog -xlower -xcomment -xempty -xndata eebodat0.sgm  | xmllint --format - > eebodat0.xml
