#!\c:\apps\perl\bin\perl.exe

#Create a valid xml charent file from the characters in 
#the charmap.sgm file.

#use strict;

#include tcp character map subroutines
require "F:/MARKUP/code/Perl/Eebo/tcp-charmap-include.pm";

#file containing character map
my $charactermap = "F:/MARKUP/code/charents/charmap.sgm"; 

#put character map into a perl array
charmap_array($charactermap); 

#create xml ent file

print "<!-- XML character entities -->\n\n";
print "<!-- Generated by tcp-charmap-entmake-xml-all.pl on " . localtime(time) . " -->\n\n";
   
foreach $entity (@entities) {
   my $ent = content_attr('ENT','TCP');
   my $unic = substr(content_attr('EQUIV','UNIC'),1); #remove initial U
   my $comment = join(" ",content_attr('EQUIV','DESC'), content_tag("COMMENT"));
   #TODO check for multiple EQUIV and COMMENT tags
   print "<!ENTITY $ent \"&\#x$unic\;\"> <!--$comment-->\n";
}
print "\n";   
